# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normal
ncpus: 48
jobfs: 10GB
mem: 100GB

walltime: 00:30:00
jobname: 1deg_jra55do_ryf_wombatlite

model: access-om3

exe: access-om3-MOM6
input:
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
    - /g/data/vk83/configurations/inputs/access-om3/share/grids/global.1deg/2020.10.22/topog.nc
    - /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.1deg/2020.05.30/ocean_mosaic.nc
    - /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.1deg/2024.05.08/grid_spec.nc
    - /g/data/vk83/configurations/inputs/access-om3/mom/surface_salt_restoring/global.1deg/2020.05.30/salt_sfc_restore.nc
    - /g/data/vk83/configurations/inputs/access-om3/cice/grids/global.1deg/2024.05.14/grid.nc
    - /g/data/vk83/configurations/inputs/access-om3/cice/grids/global.1deg/2024.05.14/kmt.nc
    - /g/data/vk83/configurations/inputs/access-om3/cice/initial_conditions/global.1deg/2023.07.28/iced.1900-01-01-10800.nc
    - /g/data/vk83/configurations/inputs/access-om3/wombat/initial_conditions/global.1deg/2024.04.02/init_ocean_wombatlite.res.nc
    - /g/data/vk83/configurations/inputs/access-om3/wombat/forcing/global.1deg/2022.02.24/dust.nc
    - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/hgrid.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/vcoord.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/bathymetry.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/init_tracers.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/init_eta.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/init_vel.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/forcing_obc_segment_001.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/forcing_obc_segment_002.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/forcing_obc_segment_003.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/forcing_obc_segment_004.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tu_segment_001.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tu_segment_002.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tu_segment_003.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tu_segment_004.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tz_segment_001.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tz_segment_002.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tz_segment_003.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/tz_segment_004.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/grid_spec.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/ocean_mosaic.nc 
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/access-rom3-ESMFmesh.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/access-rom3-nomask-ESMFmesh.nc
    - /scratch/x77/ee8016/regional_mom6_configs/trying_bgc/land_mask.nc
 
collate: false
runlog: false
metadata: 
    enable: false

userscripts: {}
    #setup: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/setup.sh
    #archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh

modules:
    use:
        - /g/data/vk83/prerelease/modules
    load:
        - access-om3/pr75-1
        - nco/5.0.5

payu_minimum_version: 1.1.6
